// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lavdsrlybprnxnheffgl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxhdmRzcmx5YnBybnhuaGVmZmdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY5MjQ2OTUsImV4cCI6MjA1MjUwMDY5NX0.LWCOI7w8-PwnH8rJy93fKa0C4OEumE_J9X5V2jZvWlI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);